swagger: '2.0'
info:
  description: This API  manage orders
  version: 1.0.0
  title: Order API
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://unlicense.org'
basePath: /api
tags:
  - name: orders-api-controller
    description: the orders API
paths:
  '/orders':
    get:
      tags:
        - Order
      summary: Get all
      operationId: getAll
      produces:
        - application/json
      parameters:

      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/order'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

definitions:
  order:
    type: object
    properties:
      customerId:
        type: string
      orderId:
        type: string
      amount:
        type: number
        format: double
      productCategory:
        type: string
      productDescription:
        type: string
      productId:
        type: string